"""Add treasuredrop table

Revision ID: f1a0b7de3ad9
Revises: 0c9defccff22
Create Date: 2020-08-06 23:51:36.253827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a0b7de3ad9'
down_revision = '0c9defccff22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasure_drop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('drop1', sa.Integer(), nullable=True),
    sa.Column('drop2', sa.Integer(), nullable=True),
    sa.Column('drop3', sa.Integer(), nullable=True),
    sa.Column('drop4', sa.Integer(), nullable=True),
    sa.Column('drop5', sa.Integer(), nullable=True),
    sa.Column('drop6', sa.Integer(), nullable=True),
    sa.Column('drop7', sa.Integer(), nullable=True),
    sa.Column('drop8', sa.Integer(), nullable=True),
    sa.Column('drop9', sa.Integer(), nullable=True),
    sa.Column('drop10', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drop1'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop10'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop2'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop3'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop4'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop5'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop6'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop7'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop8'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['drop9'], ['item_drop.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treasure_drop')
    # ### end Alembic commands ###
